### ISSUE TITLE
Indexing for CSV Resource Type Updater?

### ISSUE THREAD

**Issue by kleinlain** [Adobe-Consulting-Services/acs-aem-tools#176] opened 2017-03-01 17:06 UTC
Hello,

I use aem-tools 0.0.40 on aem 6.2 (with the oak hotfixes for version 1.4.10)
I set up an oak property index for cq:template.
My test was a change to cq:template. When I use the same query in crx query tool, I get an empty result on the first try.

Query being 
```SELECT * FROM [nt:base] WHERE ISDESCENDANTNODE([/content]) AND ([cq:template] = '﻿/my/path/to/template')```

It is possible to get a result for this query, be creating first one that checks only for the node

```SELECT * FROM [nt:base] WHERE ISDESCENDANTNODE([/content/more/deeply/to/make/it/shorter])```

Then adding a WHERE clause 

```SELECT * FROM [nt:base] WHERE ISDESCENDANTNODE([/content/more/deeply/to/make/it/shorter]) AND ([cq:template] = '/apps/another/template/to/ensure/matches')```

Then going back up to the main /content path

```SELECT * FROM [nt:base] WHERE ISDESCENDANTNODE([/content]) AND ([cq:template] = '/apps/another/template/to/ensure/matches')```

Then successfully run the original query
Query being ```SELECT * FROM [nt:base] WHERE ISDESCENDANTNODE([/content]) AND ([cq:template] = '﻿/my/path/to/template')```

However, when I then try to use the Resource Type Updater with `cq:template` Property again, the result is empty and no errors in the log.

I am really confused here, either I have serious trouble with my indexing, or - as I hope - I made some really stupid mistake?

**Comment by davidjgonzalez** [comment] 2017-03-01 18:54
Hi @kleinlain  im not sure i follow the question --what exactly are you trying to do? All this tool does is find all resources under a given path that have a cq:template = <source-value>' and updates them with the <destination-value> type. It doesnt do any tricky with extra checks or anything; its fairly dumb :)

**Comment by kleinlain** [comment] 2017-03-01 21:48
Actually I was trying to find an explanation why the "dumb" tool does not find anything to replace, although it should. 
And since it seems to try to find something by query, I tried reproducing it, hence the long and boring story above :)

**Comment by davidjgonzalez** [comment] 2017-03-02 02:18
Ahh - so were you able to figure it out?  If not could you package up one of the pages that should be done updated along w the csv file, and attach to the ticket (or email it to me direct if it has info you'd rather not share publicly? davidjgonzalez@gmail.com)

**Comment by kleinlain** [comment] 2017-03-03 15:07
No, still confused. David, I will happily send you a package on monday.

**Comment by kleinlain** [comment] 2017-03-06 17:41
So, I can manage the same with samplecontent.

and the csv simply contains 
/apps/geometrixx/templates/homepage,/apps/geometrixx-outdoors/templates/page_home

maybe I misunderstood something completely here, but I expected 
/content/geometrixx/en/jcr:content
to get the new cq:template property "/apps/geometrixx-outdoors/templates/page_home"

[resourceupdate_test.zip](https://github.com/Adobe-Consulting-Services/acs-aem-tools/files/821965/resourceupdate_test.zip)

thanks for any hints

**Comment by davidjgonzalez** [comment] 2017-03-10 13:43
@kleinlain works for me .. best i can think if youre forgetting to change the "Property Name" to `cq:template` and youre running it as a `sling:resourceType` update?

Test csv: [test.csv.txt](https://github.com/Adobe-Consulting-Services/acs-aem-tools/files/834063/test.csv.txt)

![before](https://cloud.githubusercontent.com/assets/1451868/23797345/65b1be6a-056d-11e7-9645-f8c82244c081.png)
![after](https://cloud.githubusercontent.com/assets/1451868/23797358/72baa702-056d-11e7-8b19-220e32637d99.png)

**Comment by davidjgonzalez** [comment] 2017-03-27 02:33
@kleinlain did you get this sorted out? I was unable to reproduce w the supplied files so closing. If you are still having problems please comment/re-open

**Closed by davidjgonzalez** 2017-03-27 02:33 UTC
