### ISSUE TITLE
AEM Fiddle not working with AEM 6.5.16

### ISSUE THREAD

**Issue by cmariaxavier** [Adobe-Consulting-Services/acs-aem-tools#242] opened 2023-04-04 13:07 UTC
We are having some trouble using AEM fiddle (ACS AEM tool) on instances where Service Pack 16 is installed. 

It is not possible to select a language by clicking on the "+" icon now

ACS commons tool version we have  is 1.0.2 which is the latest available version of ACS AEM Tool 
![image](https://user-images.githubusercontent.com/114423302/229801156-599ce313-5774-446b-a50f-6499591bc3bf.png)

**Comment by davidjgonzalez** [comment] 2023-04-04 14:35
are there errors in the JS console?

**Comment by cmariaxavier** [comment] 2023-04-04 14:37
Yes there are some 404 errors in the console 
![image](https://user-images.githubusercontent.com/114423302/229827368-60b8cd1d-7e07-4168-94e4-1985c20ac2c2.png)

**Comment by davidjgonzalez** [comment] 2023-04-04 15:52
took a quick look - i cant reproduce but not sure what is preventing all the supporting JS from loading. Fiddle is loading JS from /etc .. but moving it over to /apps + proxy may be quite a bit of work, and im not sure if it would work based on how the Ace editor works.

**Comment by cmariaxavier** [comment] 2023-04-04 15:55
@davidjgonzalez  This is the issue only after upgrading to SP 16. We tried on OOTB vanilla instance and the issue persists there as well

**Comment by davidjgonzalez** [comment] 2023-04-04 17:01
@cmariaxavier yeah. i can reproduce as well. i assume something changed with how clientlibs works and/or how js/css can be resolved/served.

**Comment by AlexLumo** [comment] 2023-07-11 14:53
Hi all, it looks like the root cause is in the `/libs/clientlibs/granite/coralui3/js/all.js`:
`$(document).on('touchstart.popover.data-api click.popover.data-api', '[data-toggle="popover"]',function(event) {` event listener is duplicated in JS file, causing opening and closing popover during one render cycle, which looks like popover isn't opened at all.
cc @davidjgonzalez

**Comment by davidjgonzalez** [comment] 2023-07-11 15:05
@AlexLumo is this duplicated in a AEM file? Or is that file getting loaded twice?

**Comment by AlexLumo** [comment] 2023-07-11 15:09
@davidjgonzalez it's duplicated in the file

**Comment by davidjgonzalez** [comment] 2023-07-11 15:17
@AlexLumo any idea is a bug was logged w/ Adobe support for this? (Sounds like a product bug?)

**Comment by davidjgonzalez** [comment] 2023-07-11 16:33
@AlexLumo can you try adding this to the bottom of your aemfiddle.jsp? It will remove all but 1 of the coral popover event listeners.

https://github.com/Adobe-Consulting-Services/acs-aem-tools/blob/96379fcd57353ee6817c59f6fece7befff2e4411/content/src/main/content/jcr_root/apps/acs-tools/components/aemfiddle/aemfiddle.jsp#L107-L131

**Comment by davidjgonzalez** [comment] 2023-07-11 17:49
its in Tools v1.0.4 (zip is on on Github releases)

**Closed by davidjgonzalez** 2023-07-11 17:49 UTC
